---
name: Krakend lint

on:
  pull_request:
    paths:
      - 'argocd/production/cluster-config/krakend.yaml'
      - 'argocd/staging2/cluster-config/krakend.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        krakend-app:
          - argocd/production/cluster-config/krakend.yaml
          - argocd/staging2/cluster-config/krakend.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          check-latest: true

      - name: Get krakend config from Argo App
        uses: mikefarah/yq@master
        id: krakendcfg
        with:
          cmd: yq '.spec.source.helm.valuesObject.krakend.config' ${{ matrix.krakend-app }}

      - name: persist krakend config in temp
        run: |
          cat <<EOF > /tmp/krakend.json
          ${{ steps.krakendcfg.outputs.result }}
          EOF

      - name: Run krakend check
        run: |
          # krakend check needs the --config flag
          # docker run -it devopsfaith/krakend
          docker run -i -v /tmp/krakend.json:/tmp/krakend.json devopsfaith/krakend check --config /tmp/krakend.json
