---
name: "Security"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Security Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "fs"
          scanners: vuln,secret,config
          severity: HIGH,CRITICAL
          skip-dirs: "argocd/staging/database-provisioning,argocd/production/database-provisioning,argocd/staging2/database-provisioning,argocd/sandbox/database-provisioning"
          exit-code: 1
          ignore-unfixed: true
