---
version: '3'

tasks:
  test:
    cmds:
      - go test -v ./...

  build:
    cmds:
      - go build -o ./bin/ ./...

  lint:
    cmds:
      - golangci-lint run --timeout 5m0s --config .golangci.yml